services:
  - type: web
    name: environmental-data-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: EXCEL_FILE
        value: /data/environmental_data.xlsx
    disk:
      name: data-disk
      mountPath: /data
